export const ACTION__TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_LOADING: 'SET_LOADING',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	ADD_PPRODUCT_CART: 'ADD_PPRODUCT_CART',

	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',

	SET_GROUPS_DATA: 'SET_GROUPS_DATA',
	EDIT_GROUP: 'EDIT_GROUP',
	REMOVE_GROUP: 'REMOVE_GROUP',
	ADD_GROUP: 'ADD_GROUP',
};
