export const ACTION__TYPE = {
	SET_USER: 'SET_USER',

	SET_USERS: 'SET_USERS',
	SET_ROLES: 'SET_ROLES',
	EDIT_USER: 'EDIT_USER',
	REMOVE_USER: 'REMOVE_USER',
	USER_ERROR: 'USER_ERROR',
	USER_RESET_ERROR: 'USER_RESET_ERROR',

	AUTH_ERROR: 'AUTH_ERROR',
	AUTH_RESET_ERROR: 'AUTH_RESET_ERROR',

	LOGOUT: 'LOGOUT',
	SET_LOADING: 'SET_LOADING',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	OPEN_ERROR_MODAL: 'OPEN_ERROR_MODAL',
	CLOSE_ERROR_MODAL: 'CLOSE_ERROR_MODAL',


	SET_PRODUCT_TO_CART: 'SET_PRODUCT_TO_CART',
	ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
	DEC_PRODUCT_TO_CART: 'DEC_PRODUCT_TO_CART',
	REMOVE_PRODUCT_TO_CART: 'REMOVE_PRODUCT_TO_CART',
	CLEAR_PRODUCT_TO_CART: 'CLEAR_PRODUCT_TO_CART',
	CART_ERROR: 'CART_ERROR',
	CART_RESET_ERROR: 'CART_RESET_ERROR',

	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
	EDIT_PRODUCT: 'EDIT_PRODUCT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',
	PRODUCT_ERROR: 'PRODUCT_ERROR',
	PRODUCT_RESET_ERROR: 'PRODUCT_RESET_ERROR',

	SET_GROUPS_DATA: 'SET_GROUPS_DATA',
	EDIT_GROUP: 'EDIT_GROUP',
	REMOVE_GROUP: 'REMOVE_GROUP',
	ADD_GROUP: 'ADD_GROUP',
	GROUP_ERROR: 'GROUP_ERROR',
	GROUP_RESET_ERROR: 'GROUP_RESET_ERROR',
};
