export const ACTION__TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	ADD_PPRODUCT_CART: 'ADD_PPRODUCT_CART',
};
